export const initialFretboardState = [
  [
    { name: "F", value: false },
    { name: "Gb", value: false },
    { name: "G", value: false },
    { name: "Ab", value: false },
    { name: "A", value: false },
    { name: "Bb", value: false },
    { name: "B", value: false },
    { name: "C", value: false },
    { name: "Db", value: false },
    { name: "D", value: false },
    { name: "Eb", value: false },
    { name: "E", value: false },
  ],
  [
    { name: "C", value: false },
    { name: "Db", value: false },
    { name: "D", value: false },
    { name: "Eb", value: false },
    { name: "E", value: false },
    { name: "F", value: false },
    { name: "Gb", value: false },
    { name: "G", value: false },
    { name: "Ab", value: false },
    { name: "A", value: false },
    { name: "Bb", value: false },
    { name: "B", value: false },
  ],
  [
    { name: "Ab", value: false },
    { name: "A", value: false },
    { name: "Bb", value: false },
    { name: "B", value: false },
    { name: "C", value: false },
    { name: "Db", value: false },
    { name: "D", value: false },
    { name: "Eb", value: false },
    { name: "E", value: false },
    { name: "F", value: false },
    { name: "Gb", value: false },
    { name: "G", value: false },
  ],
  [
    { name: "Eb", value: false },
    { name: "E", value: false },
    { name: "F", value: false },
    { name: "Gb", value: false },
    { name: "G", value: false },
    { name: "Ab", value: false },
    { name: "A", value: false },
    { name: "Bb", value: false },
    { name: "B", value: false },
    { name: "C", value: false },
    { name: "Db", value: false },
    { name: "D", value: false },
  ],
  [
    { name: "Bb", value: false },
    { name: "B", value: false },
    { name: "C", value: false },
    { name: "Db", value: false },
    { name: "D", value: false },
    { name: "Eb", value: false },
    { name: "E", value: false },
    { name: "F", value: false },
    { name: "Gb", value: false },
    { name: "G", value: false },
    { name: "Ab", value: false },
    { name: "A", value: false },
  ],
  [
    { name: "F", value: false },
    { name: "Gb", value: false },
    { name: "G", value: false },
    { name: "Ab", value: false },
    { name: "A", value: false },
    { name: "Bb", value: false },
    { name: "B", value: false },
    { name: "C", value: false },
    { name: "Db", value: false },
    { name: "D", value: false },
    { name: "Eb", value: false },
    { name: "E", value: false },
  ],
];
